In [83]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [84]:
df = pd.read_csv("flipkart_product.csv",encoding="latin1")
df.head()

,ProductName,Price,Rate,Review,Summary
0,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Super!,Great cooler.. excellent air flow and for this...
1,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",5,Awesome,Best budget 2 fit cooler. Nice cooling
2,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,The quality is good but the power of air is de...
3,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",1,Useless product,Very bad product it's a only a fan
4,Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...,"??3,999",3,Fair,Ok ok product

In [85]:
df.drop(["ProductName","Price"],axis=1,inplace=True)
df.head()

  Rate           Review                                            Summary
0    5           Super!  Great cooler.. excellent air flow and for this...
1    5          Awesome             Best budget 2 fit cooler. Nice cooling
2    3             Fair  The quality is good but the power of air is de...
3    1  Useless product                 Very bad product it's a only a fan
4    3             Fair                                      Ok ok product

In [86]:
df["Review"].unique()

array(['Super!', 'Awesome', 'Fair', ..., 'Mast', 'Good in budget',
       'Well!!!'], shape=(1265,), dtype=object)

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189874 entries, 0 to 189873
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Rate     189873 non-null  object
 1   Review   189870 non-null  object
 2   Summary  189860 non-null  object
dtypes: object(3)
memory usage: 4.3+ MB

In [88]:
df.duplicated().sum()

np.int64(72933)

In [89]:
df.drop_duplicates(inplace=True)

In [90]:
df.shape

(116941, 3)

In [91]:
df.columns

Index(['Rate', 'Review', 'Summary'], dtype='object')

In [92]:
df.head()

  Rate           Review                                            Summary
0    5           Super!  Great cooler.. excellent air flow and for this...
1    5          Awesome             Best budget 2 fit cooler. Nice cooling
2    3             Fair  The quality is good but the power of air is de...
3    1  Useless product                 Very bad product it's a only a fan
4    3             Fair                                      Ok ok product

In [93]:
df["Rate"].value_counts()

Rate
5                                                              64289
4                                                              22198
1                                                              15419
3                                                               9988
2                                                               5042
Pigeon Favourite Electric Kettle?ÿ?ÿ(1.5 L, Silver, Black)         1
Bajaj DX 2 L/W Dry Iron                                            1
Nova Plus Amaze NI 10 1100 W Dry Iron?ÿ?ÿ(Grey & Turquoise)        1
s                                                                  1
Name: count, dtype: int64

In [94]:
df.isnull().sum()

Rate       1
Review     4
Summary    6
dtype: int64

In [95]:
df.dropna(inplace=True)

In [96]:
df["Rate"].unique()

array(['5', '3', '1', '4', '2',
       'Pigeon Favourite Electric Kettle?ÿ?ÿ(1.5 L, Silver, Black)',
       'Bajaj DX 2 L/W Dry Iron',
       'Nova Plus Amaze NI 10 1100 W Dry Iron?ÿ?ÿ(Grey & Turquoise)', 's'],
      dtype=object)

In [97]:
def Rate_(rate):
    l = ["Pigeon Favourite Electric Kettle?ÿ?ÿ(1.5 L, Silver, Black)","Bajaj DX 2 L/W Dry Iron","Nova Plus Amaze NI 10 1100 W Dry Iron?ÿ?ÿ(Grey & Turquoise)","s"]
    if rate in l:
        return 2
    return int(rate)

# Rate_("1")
df["Rate"] = df["Rate"].apply(Rate_)
df.head()

   Rate           Review                                            Summary
0     5           Super!  Great cooler.. excellent air flow and for this...
1     5          Awesome             Best budget 2 fit cooler. Nice cooling
2     3             Fair  The quality is good but the power of air is de...
3     1  Useless product                 Very bad product it's a only a fan
4     3             Fair                                      Ok ok product

In [98]:
df.shape

(116932, 3)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 116932 entries, 0 to 189867
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Rate     116932 non-null  int64
 1   Review   116932 non-null  object
 2   Summary  116932 non-null  object
dtypes: int64(1), object(2)
memory usage: 3.6+ MB

In [100]:
df["Text"] = df["Review"] + " " + df["Summary"] 
df.drop(["Review",'Summary'],axis=1,inplace=True)
df.head()

   Rate                                               Text
0     5  Super! Great cooler.. excellent air flow and f...
1     5     Awesome Best budget 2 fit cooler. Nice cooling
2     3  Fair The quality is good but the power of air ...
3     1  Useless product Very bad product it's a only a...
4     3                                 Fair Ok ok product

In [101]:
def tolower(txt):
    return txt.lower()

In [102]:
from utils.fun import remove_punc,remove_num,remove_emoj

df["Text"] = df["Text"].apply(remove_punc)
df["Text"] = df["Text"].apply(tolower)
df["Text"] = df["Text"].apply(remove_num)
df["Text"] = df["Text"].apply(remove_emoj)

df.head()

   Rate                                               Text
0     5  super great cooler excellent air flow and for ...
1     5       awesome best budget  fit cooler nice cooling
2     3  fair the quality is good but the power of air ...
3     1  useless product very bad product its a only a fan
4     3                                 fair ok ok product

In [103]:
Max_len = 100
Max_words = 10000
Embedding_dim = 100

In [104]:
from sklearn.model_selection import train_test_split

X = df.drop("Rate",axis=1)
y = df["Rate"]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [105]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train["Text"])
train_seq = tokenizer.texts_to_sequences(X_train["Text"])
train_X_pad = pad_sequences(train_seq, maxlen=Max_len, padding="post", truncating="post")
test_seq = tokenizer.texts_to_sequences(X_test["Text"])
test_X_pad = pad_sequences(test_seq, maxlen=Max_len, padding="post",truncating="post")

In [106]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier,GradientBoostingClassifier,ExtraTreesClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,f1_score

In [107]:
models = {
    "logistic_regression": LogisticRegression(),
    "Decision_tree": DecisionTreeClassifier(),
}

In [ ]:
results = []

for name,model in models.items():
    model.fit(train_X_pad,y_train)
    y_pred = model.predict(test_X_pad)
    y_pred_train = model.predict(train_X_pad)
    acc_test = accuracy_score(y_test,y_pred)
    acc_train = accuracy_score(y_train,y_pred_train)
    print(f"{name} trained")
    results.append({
        'model':name,
        'accuracy_test':acc_test,
        'accuracy_train':acc_train
    })
df_results = pd.DataFrame(results)

df_results

c:\Users\Amir sohail\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

logistic_regression trained
Decision_tree trained

                 model  accuracy_test  accuracy_train
0  logistic_regression       0.546415        0.548239
1        Decision_tree       0.912430        0.987022

In [112]:
best_modle = models["Decision_tree"]
y_pred = best_modle.predict(test_X_pad)
y_pred_train = best_modle.predict(train_X_pad)
acc_test = accuracy_score(y_test,y_pred)
acc_train = accuracy_score(y_train,y_pred_train)
print(acc_train)
print(acc_test)

0.9870222887380405
0.912429982468893

In [113]:
from joblib import dump

dump(best_modle,"best_modle.pkl")
dump(tokenizer,"tokenizer.pkl")

['tokenizer.pkl']